version: "2"

services:
  frontend:
    build:
      context: ./
      dockerfile: docker/frontend/Dockerfile
    container_name: home_page_frontend
    image: home-page-frontend
    ports:
      - 80:80
    restart: always

  backend:
    build:
      context: ./
      dockerfile: docker/backend/Dockerfile
    container_name: home_page_backend
    image: home-page-backend
    ports:
      - 18080:8080
    restart: always
    volumes:
      - ./backend/config:/var/backend/config

volumes:
  ssl:
    driver: local
