/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.danhooper.homepage;

import org.junit.jupiter.api.Test;

import static org.springframework.test.util.AssertionErrors.assertNotNull;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Application classUnderTest = new Application();
        assertNotNull("app should be creatable", classUnderTest);
    }
}
